apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-upzd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ivhg-tenant/rhtap-demo-app/hacbs-test-project-upzd@sha256:ee293dd4a4e3e68971abb64afae9574f2128479a9c0408bdba2310b8c004ff45
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
