apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-upzd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-upzd
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-upzd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-upzd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-upzd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ivhg-tenant/rhtap-demo-app/hacbs-test-project-upzd@sha256:ee293dd4a4e3e68971abb64afae9574f2128479a9c0408bdba2310b8c004ff45
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
